name: Demo view workflow
on: [workflow_dispatch]
jobs:
  Demo print:
    runs-on: windows-latest
    steps:
      - name: Print Hello words!
        run: echo Hello words Python
      - name: Print love is Python!
        run: echo I love is Python!
